### ISSUE TITLE
font-weight

### ISSUE THREAD

**Issue by Ray94520** [shaneapowell/MMM-GmailFeed#5]
I was trying to make my fonts a little bolder so they're easier to see
I noticed in the colfrom there are 2 font-weight
but in colsubj there is no font-weight . Is this a typo?

I tried to incorporate font-weight in colsubj but nothing happened
font-weight is not working there

MMM-GmailFeed .colfrom {
  width: 1px;
  padding-right: 8px;
  text-align: left;
  font-weight: 200;       <------
  white-space: nowrap;
  font-weight: 300;     <------
  font-size: 20px;
  text-align: left;

MMM-GmailFeed .colsubj {
  white-space: nowrap;
  font-size: 20px;
  text-align: left;

Hope you can help Ray

**Comment by shaneapowell** [comment]
Hi Ray. Honestly.. I don't even know  if the font-weight works as expected.   I had copied that .css from the original JsonTable repo and just sort-of went with it.  The most I could achieve was to reduce the font-weight.  that un-bolded the text.  I was not able to increase it enough to make it "more" bold.

**Comment by Ray94520** [comment]
Well what I actually did was eliminate 1 of them and copied it over to
MMM-GmailFeed .colsubj and it seemed to work. I was able to adjust the font size
it's been there for at least since I posted this on your site here and so far it seems to be working

**Comment by Sandeshbhat234** [comment]
i am getting error[null]  i don,t know why.. Can anybody tell me? thanks

**Comment by KristjanESPERANTO** [comment]
@Ray94520: I found it useful to increase the font-weight a little as you suggested. I did this in my PR #9. Let's  see if/when @shaneapowell accept it.

@Sandeshbhat234: Please do not comment on issues that are about completely different topics. Your problem was addressed in #7.

**Comment by shaneapowell** [comment]
Fixed with #9
