### ISSUE TITLE
Gmail header

### ISSUE THREAD

**Issue by Ray94520** [shaneapowell/MMM-GmailFeed#6]
So I have a question
about MMM-GmailFeed
So under Gmail header I have
 GMAIL-INBOX FOR myemail@gmail.com-14

Is there a way I can have just
GMAIL-INBOX-14

That would be awesome if I could
Ray

**Comment by KristjanESPERANTO** [comment]
@Ray94520: I found this useful too. I did this in my PR https://github.com/shaneapowell/MMM-GmailFeed/pull/9. Let's see if/when @shaneapowell accept it.

**Comment by shaneapowell** [comment]
fixed with #9
