### ISSUE TITLE
[null]

### ISSUE THREAD

**Issue by Benni23k** [shaneapowell/MMM-GmailFeed#7]
Im rly new into all of this so dont mind me xD
i keep having a [null] error and i dont know why

**Comment by KristjanESPERANTO** [comment]
Where does the error occur? When you install the module or when the module should be shown? Please show us your configuration without secrets.

**Comment by prajwalkno3** [comment]
> Where does the error occur? When you install the module or when the module should be shown? Please show us your configuration without secrets.

Its same for me also after loading npm start at bottom its showing Gmail feed null

**Comment by prajwalkno3** [comment]
> Im rly new into all of this so dont mind me xD i keep having a [null] error and i dont know why

I had same issue i solved it. 
I suggest you to enable 2 step verification in your google account, disabling it and entering Email ID & pass in modules dosent help as i already tried. Create APP password its already explained by shaneapowell in his repository, app that 16digit unique password it will work.

**Comment by KristjanESPERANTO** [comment]
@prajwalkno3 Thanks for the hint! :slightly_smiling_face: 

@shaneapowell I think you can close this issue since @prajwalkno3 presented a solution and @Benni23k didn't respond.
