### ISSUE TITLE
Download error

### ISSUE THREAD

**Issue by killua173** [shaneapowell/MMM-GmailFeed#8]
`(python-facereco) mohamad@raspberrypi:~/MMM-GmailFeed $ npm audit fix --force
npm WARN using --force Recommended protections disabled.
npm WARN audit No fix available for request@*
npm WARN audit Updating xml2js to 0.6.2, which is a SemVer major change.

changed 1 package, and audited 51 packages in 4s

2 packages are looking for funding
  run `npm fund` for details

# npm audit report

request  *
Severity: moderate
Server-Side Request Forgery in Request - https://github.com/advisories/GHSA-p8p7-x288-28g6
Depends on vulnerable versions of tough-cookie
No fix available
node_modules/request

tough-cookie  <4.1.3
Severity: moderate
tough-cookie Prototype Pollution vulnerability - https://github.com/advisories/GHSA-72xf-g2v4-qvf3
No fix available
node_modules/tough-cookie

2 moderate severity vulnerabilities

Some issues need review, and may require choosing
a different dependency.     `

**Comment by KristjanESPERANTO** [comment]
PR #9 will fix this issue. However, the module should still work despite these warnings.

**Comment by killua173** [comment]
Yeah it is working after I moved the module to modules folder ,but first I tried without doing that as it didn't stated that in the readme and I am kinda new to MMM it is working pretty good other than those two:it shows null for a secound when updating the email and the width is as much as it could be 
Thanks

**Comment by KristjanESPERANTO** [comment]
> it shows null for a secound when updating the email

I think that should be fixed with my fix as well.

> the width is as much as it could be

I don't really understand what you mean by that. Can you describe it in more detail?

**Comment by killua173** [comment]
The width of the mudele is the from screen left edge to right one unless there is other models that block the way then it looks good and the width is okay

**Comment by KristjanESPERANTO** [comment]
@killua173 Okay, I can imagine the behavior with `position: bottom_bar`. Do you have that? Please try `position: bottom_center`.
